### PR TITLE
~ migrate ShExJ to top-level ShapeDecls

### PR DESCRIPTION
**Pull request by ericprud**
per shexSpec/spec#50

### CODE REVIEW

**Review by gkellogg — COMMENTED** [review]
Are there new tests that show the advantage of this indirection rather than just the extra overhead of indirection?

**Comment by ericprud** [comment]
> Are there new tests that show the advantage of this indirection rather than just the extra overhead of indirection?

I don't think the tests show it off. The ShExJ.jsg is [a ton simpler](https://github.com/shexSpec/shexTest/pull/51/files#diff-2ce28ebfc234134f39bac3ed989e57c05fa3d92d383182e875860ffe0c7f1b4b).
I think the strongest case comes from diving into an implementation and seeing the number of potential bugs that disappear. There are lots of places where I wasn't conditionally traversing the ShapeDecls's `.shexExpr` ([e.g.](https://github.com/shexjs/shex.js/pull/103/files#diff-7ed4dcefe40c6a75f2223de310ce8c9a311e5a08823ebee92e71b480f266d011L532)) because I hadn't happened to hit those lines with a schema that needed a ShapeDecl (i.e. had `.abstract` set to true).

**Review by gkellogg — APPROVED** [review]

**Comment by ericprud** [comment]
Tx @gkellogg . I'll wait 'till Iovka gets shex-java running with the current extensd tests before pushing this upstream with the idea of making her steps to passing the tests more incremental.
@iovka, that may require you to do extra coding so if you prefer, just you can merge this into extends and and pull the merged extends.

**Comment by ericprud** [comment]
Labra vocalized his approval in EXTENDS meeting on 2022-07-05

**Pull request merged**
